Read me
aepaysinger/code-challenges-javascript pull request #17
Opened 2023-04-14 16:53 UTC by aepaysinger

it has been so long since i did this i wanted to make sure this was looking okay

2023-04-14 17:44 UTC, W-Ely requested changes
Minor changes

2023-04-14 17:44 UTC, W-Ely commented on README.md
> +git clone <path>
```suggestion
glt clone https://github.com/aepaysinger/code-challenges-javascript.git
```

2023-04-14 17:44 UTC, W-Ely commented on README.md
> +```
This is incorrect.  `jest` is already listed as a development dependency in your [package.json ](https://github.com/aepaysinger/code-challenges-javascript/blob/main/package.json#L20)

JavaScript how to install dev dependencies package.json.

2023-04-14 17:44 UTC, W-Ely commented on README.md
> +}
What is this step?  If they cloned down the repo, the package.json is the one from the repo.

2023-05-01 17:33 UTC, aepaysinger commented
is there anything else i need to change?

2023-05-01 17:36 UTC, W-Ely commented
Steps 2 and 3 are still wrong.

2023-05-02 14:09 UTC, aepaysinger commented
so i updated it a while ago and didnt realize i was having issues with pushing it through. when i go to git push read-me, it says:  ! [rejected]        read-me -> read-me (non-fast-forward)
error: failed to push some refs to 'https://github.com/aepaysinger/code-challenges-javascript.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
i have tried merging with main but it is already up to date.....

2023-05-02 16:06 UTC, W-Ely commented
> i have tried merging with main but it is already up to date.....

What does the `hint` mean to you?  Have you checked Github to see what the read-me branch looks like?

2023-05-02 17:07 UTC, aepaysinger commented
i have checked git hub and the read me branch doesnt look the way i want it too. i need to push what i have on the branch locally. 
im not sure what it means by the tip of current branch is behind.
do i need to checkout out to main and then git pull read-me?

2023-05-03 01:39 UTC, W-Ely commented
Are the few file deletions intended here?

2023-05-03 12:39 UTC, aepaysinger commented
yes.

2023-05-03 13:31 UTC, W-Ely reviewed
> yes.

Why?

[src/challenges/price_of_magoes.js](https://github.com/aepaysinger/code-challenges-javascript/pull/17/files#diff-d53443bba1f4066f2087963947ea99cbd87ed7e1e33e422a389a31e70ddb49a7) -- This file has a corresponding .test.js file.  If you remove it main will be in a failing state.

[src/tests/example.test.js](https://github.com/aepaysinger/code-challenges-javascript/pull/17/files#diff-340bf2619b23e272115ba5645b54d75b0c643283d208705d4bfd8bd50ffb4a10) -- example.js remains so why delete the test?

[src/tests/reduce_but_grow.test.js](https://github.com/aepaysinger/code-challenges-javascript/pull/17/files#diff-257d1e983b9bd0e762451eabdb208439556730b8219b727d78934f2c4d3cb049) -- same reduce_but_grow remains so why delete the test?

> it has been so long since i did this i wanted to make sure this was looking okay
VScode lets you preview markdown locally, have you taken a look?  also you can navigate to the branch here https://github.com/aepaysinger/code-challenges-javascript/tree/read-me to see how it will actually look in Github.

When writing instructions for setup, you should make an effort to ensure that they actually work by at least cloning down the repo fresh or into a new location and walking the steps you lay out.

2023-05-03 13:31 UTC, W-Ely commented on README.md
> +npm install --production
What does `--production` do?  Didn't work for me
```
[6:27:59] ➜  code-challenges-javascript git:(main) npm install --production
npm WARN config production Use `--omit=dev` instead.

up to date, audited 1 package in 362ms

found 0 vulnerabilities
[6:28:07] ➜  code-challenges-javascript git:(main) npm test

> code-challenges-javascript@1.0.0 test
> jest

sh: jest: command not found
[6:28:28] ➜  code-challenges-javascript git:(main)
```
https://docs.npmjs.com/cli/v9/commands/npm-install

2023-05-31 15:06 UTC, W-Ely approved these changes

2023-05-31 15:06 UTC, W-Ely commented on README.md
> +cd name of directory
```suggestion
cd <path to directory>
```

2023-05-31 15:10 UTC, W-Ely commented
> Are the few file deletions intended here?
> >yes.

> Why?
[src/challenges/price_of_magoes.js](https://github.com/aepaysinger/code-challenges-javascript/pull/17/files#diff-d53443bba1f4066f2087963947ea99cbd87ed7e1e33e422a389a31e70ddb49a7) -- This file has a corresponding .test.js file. If you remove it main will be in a failing state.
[src/tests/example.test.js](https://github.com/aepaysinger/code-challenges-javascript/pull/17/files#diff-340bf2619b23e272115ba5645b54d75b0c643283d208705d4bfd8bd50ffb4a10) -- example.js remains so why delete the test?
[src/tests/reduce_but_grow.test.js](https://github.com/aepaysinger/code-challenges-javascript/pull/17/files#diff-257d1e983b9bd0e762451eabdb208439556730b8219b727d78934f2c4d3cb049) -- same reduce_but_grow remains so why delete the test?

Still applies, but the readme now looks good. This is also now an additional unrelated file addition.

2023-05-31 18:39 UTC, aepaysinger commented
if its already on main would deleting it from this branch delete from main?

2023-06-01 15:19 UTC, closed without merging